### PR TITLE
Add clusto-attr-tree script

### PR DESCRIPTION
**Pull request by daradib**
Script displays clusto object attributes, optionally including indented parent container object attributes recursively and representing keys, subkeys, and values in different colors.

### CODE REVIEW

**Comment by thekad** [comment]
We already have a "clusto-tree" script, is there any chance to just add the attribute display functionality to it? like adding an extra argument to clusto-tree to print attributes...

**Comment by daradib** [comment]
That is a possibility, but currently the scripts recurse in opposite directions (into contents vs. into parents) because they answer different recursive questions (what is contained in this object vs. what attributes does this object have, inherited from parents). Not as useful to print the attributes of every contained object. Should I update `clusto-tree` to support both use cases, and add support for `argparse`, `script_helper.Script`, colors, etc, even if this changes the format of the output?

**Comment by daradib** [comment]
@thekad I combined clusto-attr-tree and clusto-tree, does this look reasonable to you?

**Comment by thekad** [comment]
@daradib I don't have this branch checked out on this laptop, can you gist a sample of either output? I think it looks fine from the code itself but I'm curious.

**Comment by daradib** [comment]
[Sample output with dummy objects](https://gist.github.com/daradib/cae4b9d320a49d33fe8a)

**Comment by thekad** [comment]
LGTM now.

**Pull request merged**
