### PR TITLE
addattr to support relational and integer values

### PR DESCRIPTION
**Pull request by AltanAlpay**
to be able to execute requests like 
GET /pool/foobar/addattr?key=foo&subkey=bar&value=/server/foobar01&datatype=relation 
GET /pool/foobar/addattr?key=foo&subkey=bar&value=1&datatype=int

### CODE REVIEW

**Comment by thekad** [comment]
-1 on this, if this is intended for the httpd interface then clusto-httpd should have a method for pools to insert things into them (which it might already have?) instead of modifying core methods.

**Comment by AltanAlpay** [comment]
Yes, there are already insert and remove methods for pools. This is to improve addattr method (which already exists) to accept datatype=relation, in order to put an object as attribute.

**Comment by AltanAlpay** [comment]
and to addattr as integer, at time being, all attributes assumed as string.

**Comment by AltanAlpay** [comment]
I've reverted few redundant lines at add_attr()

**Comment by thekad** [comment]
LGTM to me now, another +1 anyone?

**Comment by JeremyGrosser** [comment]
+1 merging.

**Pull request merged**
